# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drawing.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 720)
        MainWindow.setMinimumSize(QtCore.QSize(600, 360))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 720))
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.Drawing = QtWidgets.QPushButton(self.centralwidget)
        self.Drawing.setGeometry(QtCore.QRect(0, 0, 130, 30))
        self.Drawing.setMinimumSize(QtCore.QSize(130, 30))
        self.Drawing.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Drawing.setFont(font)
        self.Drawing.setStyleSheet("border: none; background-color: rgb(209, 196, 255)")
        self.Drawing.setObjectName("Drawing")
        self.Effects = QtWidgets.QPushButton(self.centralwidget)
        self.Effects.setGeometry(QtCore.QRect(260, 0, 130, 30))
        self.Effects.setMinimumSize(QtCore.QSize(130, 30))
        self.Effects.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Effects.setFont(font)
        self.Effects.setStyleSheet("border: none; background-color: rgb(126, 87, 194)")
        self.Effects.setObjectName("Effects")
        self.drawing_buttons = QtWidgets.QPushButton(self.centralwidget)
        self.drawing_buttons.setGeometry(QtCore.QRect(0, 30, 2400, 80))
        self.drawing_buttons.setMinimumSize(QtCore.QSize(130, 80))
        self.drawing_buttons.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drawing_buttons.setFont(font)
        self.drawing_buttons.setStyleSheet("border: none; background-color: rgb(209, 196, 255)")
        self.drawing_buttons.setText("")
        self.drawing_buttons.setObjectName("drawing_buttons")
        self.Area = QtWidgets.QScrollArea(self.centralwidget)
        self.Area.setEnabled(True)
        self.Area.setGeometry(QtCore.QRect(70, 120, 1120, 550))
        self.Area.setStyleSheet("background-color: rgb(200, 200, 200)")
        self.Area.setFrameShape(QtWidgets.QFrame.Box)
        self.Area.setLineWidth(1)
        self.Area.setMidLineWidth(1)
        self.Area.setWidgetResizable(True)
        self.Area.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Area.setObjectName("Area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1114, 544))
        self.scrollAreaWidgetContents.setStyleSheet("background-color: rgb(200, 200, 200)")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Area.setWidget(self.scrollAreaWidgetContents)
        self.btn_Save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Save.setGeometry(QtCore.QRect(5, 35, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Save.setFont(font)
        self.btn_Save.setAutoFillBackground(False)
        self.btn_Save.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Save.setObjectName("btn_Save")
        self.btn_Open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Open.setGeometry(QtCore.QRect(5, 70, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Open.setFont(font)
        self.btn_Open.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Open.setObjectName("btn_Open")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(140, 35, 3, 65))
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.sld_Width = QtWidgets.QSlider(self.centralwidget)
        self.sld_Width.setGeometry(QtCore.QRect(230, 75, 120, 30))
        self.sld_Width.setMinimumSize(QtCore.QSize(0, 30))
        self.sld_Width.setStyleSheet("background-color: rgb(200, 187, 250)")
        self.sld_Width.setMinimum(1)
        self.sld_Width.setMaximum(250)
        self.sld_Width.setProperty("value", 1)
        self.sld_Width.setTracking(True)
        self.sld_Width.setOrientation(QtCore.Qt.Horizontal)
        self.sld_Width.setObjectName("sld_Width")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 70, 80, 39))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(209, 196, 255)")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.spin_Width = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_Width.setGeometry(QtCore.QRect(355, 76, 65, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spin_Width.setFont(font)
        self.spin_Width.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spin_Width.setFrame(False)
        self.spin_Width.setMinimum(1)
        self.spin_Width.setMaximum(250)
        self.spin_Width.setObjectName("spin_Width")
        self.btn_Crop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Crop.setGeometry(QtCore.QRect(150, 35, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Crop.setFont(font)
        self.btn_Crop.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Crop.setObjectName("btn_Crop")
        self.btn_Copy = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Copy.setGeometry(QtCore.QRect(255, 35, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_Copy.setFont(font)
        self.btn_Copy.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Copy.setObjectName("btn_Copy")
        self.btn_Paste = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Paste.setGeometry(QtCore.QRect(465, 35, 95, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Paste.setFont(font)
        self.btn_Paste.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Paste.setObjectName("btn_Paste")
        self.btn_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Delete.setGeometry(QtCore.QRect(370, 35, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Delete.setFont(font)
        self.btn_Delete.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Delete.setObjectName("btn_Delete")
        self.btn_Select = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Select.setGeometry(QtCore.QRect(10, 125, 50, 50))
        self.btn_Select.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Select.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Select.setText("")
        self.btn_Select.setIconSize(QtCore.QSize(40, 40))
        self.btn_Select.setObjectName("btn_Select")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(565, 35, 3, 65))
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Picture = QtWidgets.QPushButton(self.centralwidget)
        self.Picture.setGeometry(QtCore.QRect(130, 0, 130, 30))
        self.Picture.setMinimumSize(QtCore.QSize(130, 30))
        self.Picture.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Picture.setFont(font)
        self.Picture.setStyleSheet("border: none; background-color: rgb(126, 87, 194)")
        self.Picture.setObjectName("Picture")
        self.instruments = QtWidgets.QPushButton(self.centralwidget)
        self.instruments.setGeometry(QtCore.QRect(5, 120, 60, 535))
        self.instruments.setMinimumSize(QtCore.QSize(60, 80))
        self.instruments.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.instruments.setFont(font)
        self.instruments.setStyleSheet("border: none; background-color: rgb(209, 196, 255)")
        self.instruments.setText("")
        self.instruments.setObjectName("instruments")
        self.btn_Pipette = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Pipette.setGeometry(QtCore.QRect(10, 190, 50, 50))
        self.btn_Pipette.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Pipette.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_Pipette.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Pipette.setText("")
        self.btn_Pipette.setIconSize(QtCore.QSize(40, 40))
        self.btn_Pipette.setObjectName("btn_Pipette")
        self.btn_Eraser = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Eraser.setGeometry(QtCore.QRect(10, 245, 50, 50))
        self.btn_Eraser.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Eraser.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_Eraser.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Eraser.setText("")
        self.btn_Eraser.setIconSize(QtCore.QSize(40, 40))
        self.btn_Eraser.setObjectName("btn_Eraser")
        self.lbl_color1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_color1.setGeometry(QtCore.QRect(735, 35, 95, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_color1.setFont(font)
        self.lbl_color1.setStyleSheet("background-color: rgba(128, 128, 128, 128);")
        self.lbl_color1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_color1.setObjectName("lbl_color1")
        self.lbl_color2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_color2.setGeometry(QtCore.QRect(735, 70, 95, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_color2.setFont(font)
        self.lbl_color2.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.lbl_color2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_color2.setObjectName("lbl_color2")
        self.color_label1 = QtWidgets.QPushButton(self.centralwidget)
        self.color_label1.setGeometry(QtCore.QRect(695, 35, 30, 30))
        self.color_label1.setMinimumSize(QtCore.QSize(30, 30))
        self.color_label1.setMaximumSize(QtCore.QSize(30, 30))
        self.color_label1.setStyleSheet("border: none; background-color: black")
        self.color_label1.setText("")
        self.color_label1.setObjectName("color_label1")
        self.color_label2 = QtWidgets.QPushButton(self.centralwidget)
        self.color_label2.setGeometry(QtCore.QRect(695, 70, 30, 30))
        self.color_label2.setMinimumSize(QtCore.QSize(30, 30))
        self.color_label2.setMaximumSize(QtCore.QSize(30, 30))
        self.color_label2.setStyleSheet("border: none; background-color: white")
        self.color_label2.setText("")
        self.color_label2.setObjectName("color_label2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(840, 36, 291, 64))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.listColors = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.listColors.setContentsMargins(1, 1, 1, 1)
        self.listColors.setHorizontalSpacing(1)
        self.listColors.setVerticalSpacing(0)
        self.listColors.setObjectName("listColors")
        self.c1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c1.setMinimumSize(QtCore.QSize(30, 30))
        self.c1.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c1.setFont(font)
        self.c1.setStyleSheet("border: none; background-color: black")
        self.c1.setText("")
        self.c1.setObjectName("c1")
        self.listColors.addWidget(self.c1, 0, 0, 1, 1)
        self.c16 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c16.setMinimumSize(QtCore.QSize(30, 30))
        self.c16.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c16.setFont(font)
        self.c16.setStyleSheet("border: none; background-color: darkturquoise")
        self.c16.setText("")
        self.c16.setObjectName("c16")
        self.listColors.addWidget(self.c16, 1, 9, 1, 1)
        self.c9 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c9.setMinimumSize(QtCore.QSize(30, 30))
        self.c9.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c9.setFont(font)
        self.c9.setStyleSheet("border: none; background-color: purple")
        self.c9.setText("")
        self.c9.setObjectName("c9")
        self.listColors.addWidget(self.c9, 0, 11, 1, 1)
        self.c15 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c15.setMinimumSize(QtCore.QSize(30, 30))
        self.c15.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c15.setFont(font)
        self.c15.setStyleSheet("border: none; background-color: lightgreen")
        self.c15.setText("")
        self.c15.setObjectName("c15")
        self.listColors.addWidget(self.c15, 1, 8, 1, 1)
        self.c6 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c6.setMinimumSize(QtCore.QSize(30, 30))
        self.c6.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c6.setFont(font)
        self.c6.setStyleSheet("border: none; background-color: darkgreen")
        self.c6.setText("")
        self.c6.setObjectName("c6")
        self.listColors.addWidget(self.c6, 0, 8, 1, 1)
        self.c5 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c5.setMinimumSize(QtCore.QSize(30, 30))
        self.c5.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c5.setFont(font)
        self.c5.setStyleSheet("border: none; background-color: yellow")
        self.c5.setText("")
        self.c5.setObjectName("c5")
        self.listColors.addWidget(self.c5, 0, 7, 1, 1)
        self.c4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c4.setMinimumSize(QtCore.QSize(30, 30))
        self.c4.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c4.setFont(font)
        self.c4.setStyleSheet("border: none; background-color: orange")
        self.c4.setText("")
        self.c4.setObjectName("c4")
        self.listColors.addWidget(self.c4, 0, 5, 1, 1)
        self.c12 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c12.setMinimumSize(QtCore.QSize(30, 30))
        self.c12.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c12.setFont(font)
        self.c12.setStyleSheet("border: none; background-color: pink")
        self.c12.setText("")
        self.c12.setObjectName("c12")
        self.listColors.addWidget(self.c12, 1, 4, 1, 1)
        self.c13 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c13.setMinimumSize(QtCore.QSize(30, 30))
        self.c13.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c13.setFont(font)
        self.c13.setStyleSheet("border: none; background-color: gold")
        self.c13.setText("")
        self.c13.setObjectName("c13")
        self.listColors.addWidget(self.c13, 1, 5, 1, 1)
        self.c7 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c7.setMinimumSize(QtCore.QSize(30, 30))
        self.c7.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c7.setFont(font)
        self.c7.setStyleSheet("border: none; background-color: lightblue")
        self.c7.setText("")
        self.c7.setObjectName("c7")
        self.listColors.addWidget(self.c7, 0, 9, 1, 1)
        self.c3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c3.setMinimumSize(QtCore.QSize(30, 30))
        self.c3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c3.setFont(font)
        self.c3.setStyleSheet("border: none; background-color: red")
        self.c3.setText("")
        self.c3.setObjectName("c3")
        self.listColors.addWidget(self.c3, 0, 4, 1, 1)
        self.c2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c2.setMinimumSize(QtCore.QSize(30, 30))
        self.c2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c2.setFont(font)
        self.c2.setStyleSheet("border: none; background-color: rgb(128, 128, 128)")
        self.c2.setText("")
        self.c2.setObjectName("c2")
        self.listColors.addWidget(self.c2, 0, 1, 1, 1)
        self.c18 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c18.setMinimumSize(QtCore.QSize(30, 30))
        self.c18.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c18.setFont(font)
        self.c18.setStyleSheet("border: none; background-color: violet")
        self.c18.setText("")
        self.c18.setObjectName("c18")
        self.listColors.addWidget(self.c18, 1, 11, 1, 1)
        self.c14 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c14.setMinimumSize(QtCore.QSize(30, 30))
        self.c14.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c14.setFont(font)
        self.c14.setStyleSheet("border: none; background-color: lightyellow")
        self.c14.setText("")
        self.c14.setObjectName("c14")
        self.listColors.addWidget(self.c14, 1, 7, 1, 1)
        self.c11 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c11.setMinimumSize(QtCore.QSize(30, 30))
        self.c11.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c11.setFont(font)
        self.c11.setStyleSheet("border: none; background-color: rgb(170, 170, 170)")
        self.c11.setText("")
        self.c11.setObjectName("c11")
        self.listColors.addWidget(self.c11, 1, 1, 1, 1)
        self.c17 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c17.setMinimumSize(QtCore.QSize(30, 30))
        self.c17.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c17.setFont(font)
        self.c17.setStyleSheet("border: none; background-color: CadetBlue")
        self.c17.setText("")
        self.c17.setObjectName("c17")
        self.listColors.addWidget(self.c17, 1, 10, 1, 1)
        self.c8 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c8.setMinimumSize(QtCore.QSize(30, 30))
        self.c8.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c8.setFont(font)
        self.c8.setStyleSheet("border: none; background-color: blue")
        self.c8.setText("")
        self.c8.setObjectName("c8")
        self.listColors.addWidget(self.c8, 0, 10, 1, 1)
        self.c10 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.c10.setMinimumSize(QtCore.QSize(30, 30))
        self.c10.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c10.setFont(font)
        self.c10.setStyleSheet("border: none; background-color: white")
        self.c10.setText("")
        self.c10.setObjectName("c10")
        self.listColors.addWidget(self.c10, 1, 0, 1, 1)
        self.listColors.setRowMinimumHeight(0, 32)
        self.btn_Palette = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Palette.setGeometry(QtCore.QRect(1140, 35, 50, 60))
        self.btn_Palette.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_Palette.setFont(font)
        self.btn_Palette.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Palette.setObjectName("btn_Palette")
        self.border_styles = QtWidgets.QComboBox(self.centralwidget)
        self.border_styles.setGeometry(QtCore.QRect(660, 40, 25, 24))
        self.border_styles.setStyleSheet("background-color: none;")
        self.border_styles.setObjectName("border_styles")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(585, 37, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;")
        self.label_2.setObjectName("label_2")
        self.bg_styles = QtWidgets.QComboBox(self.centralwidget)
        self.bg_styles.setGeometry(QtCore.QRect(660, 73, 25, 24))
        self.bg_styles.setStyleSheet("background-color: none;")
        self.bg_styles.setObjectName("bg_styles")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(575, 70, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: none;")
        self.label_3.setObjectName("label_3")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(5, 400, 60, 16))
        self.line_3.setStyleSheet("background-color: none;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(5, 410, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: none; background-color: rgb(209, 196, 255)")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btn_drawRect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_drawRect.setGeometry(QtCore.QRect(10, 545, 50, 50))
        self.btn_drawRect.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_drawRect.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_drawRect.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_drawRect.setText("")
        self.btn_drawRect.setIconSize(QtCore.QSize(40, 40))
        self.btn_drawRect.setObjectName("btn_drawRect")
        self.btn_drawEllipse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_drawEllipse.setGeometry(QtCore.QRect(10, 490, 50, 50))
        self.btn_drawEllipse.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_drawEllipse.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_drawEllipse.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_drawEllipse.setText("")
        self.btn_drawEllipse.setIconSize(QtCore.QSize(40, 40))
        self.btn_drawEllipse.setObjectName("btn_drawEllipse")
        self.btn_drawLine = QtWidgets.QPushButton(self.centralwidget)
        self.btn_drawLine.setGeometry(QtCore.QRect(10, 435, 50, 50))
        self.btn_drawLine.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_drawLine.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_drawLine.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_drawLine.setText("")
        self.btn_drawLine.setIconSize(QtCore.QSize(40, 40))
        self.btn_drawLine.setObjectName("btn_drawLine")
        self.btn_drawRRect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_drawRRect.setGeometry(QtCore.QRect(10, 600, 50, 50))
        self.btn_drawRRect.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_drawRRect.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_drawRRect.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_drawRRect.setText("")
        self.btn_drawRRect.setIconSize(QtCore.QSize(40, 40))
        self.btn_drawRRect.setObjectName("btn_drawRRect")
        self.label_Pos = QtWidgets.QLabel(self.centralwidget)
        self.label_Pos.setGeometry(QtCore.QRect(70, 680, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Pos.setFont(font)
        self.label_Pos.setObjectName("label_Pos")
        self.XSArea = QtWidgets.QSpinBox(self.centralwidget)
        self.XSArea.setGeometry(QtCore.QRect(550, 683, 90, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.XSArea.setFont(font)
        self.XSArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.XSArea.setFrame(False)
        self.XSArea.setMinimum(-99999)
        self.XSArea.setMaximum(99999)
        self.XSArea.setProperty("value", 0)
        self.XSArea.setObjectName("XSArea")
        self.YSArea = QtWidgets.QSpinBox(self.centralwidget)
        self.YSArea.setGeometry(QtCore.QRect(720, 683, 90, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.YSArea.setFont(font)
        self.YSArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YSArea.setFrame(False)
        self.YSArea.setMinimum(-99999)
        self.YSArea.setMaximum(99999)
        self.YSArea.setProperty("value", 0)
        self.YSArea.setObjectName("YSArea")
        self.WSArea = QtWidgets.QSpinBox(self.centralwidget)
        self.WSArea.setGeometry(QtCore.QRect(910, 683, 90, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WSArea.setFont(font)
        self.WSArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WSArea.setFrame(False)
        self.WSArea.setMinimum(-99999)
        self.WSArea.setMaximum(99999)
        self.WSArea.setProperty("value", 0)
        self.WSArea.setObjectName("WSArea")
        self.HSArea = QtWidgets.QSpinBox(self.centralwidget)
        self.HSArea.setGeometry(QtCore.QRect(1090, 683, 90, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HSArea.setFont(font)
        self.HSArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.HSArea.setFrame(False)
        self.HSArea.setMinimum(-99999)
        self.HSArea.setMaximum(99999)
        self.HSArea.setProperty("value", 0)
        self.HSArea.setObjectName("HSArea")
        self.label_Pos_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Pos_2.setGeometry(QtCore.QRect(515, 680, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Pos_2.setFont(font)
        self.label_Pos_2.setStyleSheet("background-color: rgb(209, 196, 255)")
        self.label_Pos_2.setObjectName("label_Pos_2")
        self.label_Pos_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Pos_3.setGeometry(QtCore.QRect(685, 680, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Pos_3.setFont(font)
        self.label_Pos_3.setStyleSheet("background-color: rgb(209, 196, 255)")
        self.label_Pos_3.setObjectName("label_Pos_3")
        self.label_Pos_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_Pos_4.setGeometry(QtCore.QRect(875, 680, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Pos_4.setFont(font)
        self.label_Pos_4.setStyleSheet("background-color: rgb(209, 196, 255)")
        self.label_Pos_4.setObjectName("label_Pos_4")
        self.label_Pos_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_Pos_5.setGeometry(QtCore.QRect(1055, 680, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Pos_5.setFont(font)
        self.label_Pos_5.setStyleSheet("background-color: rgb(209, 196, 255)")
        self.label_Pos_5.setObjectName("label_Pos_5")
        self.drawing_buttons_2 = QtWidgets.QPushButton(self.centralwidget)
        self.drawing_buttons_2.setGeometry(QtCore.QRect(380, 680, 810, 30))
        self.drawing_buttons_2.setMinimumSize(QtCore.QSize(130, 30))
        self.drawing_buttons_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drawing_buttons_2.setFont(font)
        self.drawing_buttons_2.setStyleSheet("border: none; background-color: rgb(209, 196, 255)")
        self.drawing_buttons_2.setText("")
        self.drawing_buttons_2.setObjectName("drawing_buttons_2")
        self.btn_Ready = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Ready.setGeometry(QtCore.QRect(385, 683, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Ready.setFont(font)
        self.btn_Ready.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Ready.setObjectName("btn_Ready")
        self.btn_Pencil = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Pencil.setGeometry(QtCore.QRect(10, 300, 50, 50))
        self.btn_Pencil.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Pencil.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_Pencil.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Pencil.setText("")
        self.btn_Pencil.setIconSize(QtCore.QSize(40, 40))
        self.btn_Pencil.setObjectName("btn_Pencil")
        self.errors = QtWidgets.QLabel(self.centralwidget)
        self.errors.setGeometry(QtCore.QRect(600, 0, 600, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.errors.setFont(font)
        self.errors.setText("")
        self.errors.setObjectName("errors")
        self.Radius = QtWidgets.QSpinBox(self.centralwidget)
        self.Radius.setGeometry(QtCore.QRect(490, 75, 65, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Radius.setFont(font)
        self.Radius.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Radius.setFrame(False)
        self.Radius.setMinimum(1)
        self.Radius.setMaximum(250)
        self.Radius.setObjectName("Radius")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(430, 78, 55, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(209, 196, 255)")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.btn_Info = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Info.setGeometry(QtCore.QRect(10, 660, 50, 50))
        self.btn_Info.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Info.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_Info.setStyleSheet("border-radius: 25px;\n"
"background-color: rgba(209, 196, 255, 150);")
        self.btn_Info.setText("")
        self.btn_Info.setIconSize(QtCore.QSize(40, 40))
        self.btn_Info.setObjectName("btn_Info")
        self.drawing_buttons_2.raise_()
        self.Drawing.raise_()
        self.Effects.raise_()
        self.drawing_buttons.raise_()
        self.Area.raise_()
        self.btn_Save.raise_()
        self.btn_Open.raise_()
        self.line.raise_()
        self.sld_Width.raise_()
        self.label.raise_()
        self.spin_Width.raise_()
        self.btn_Crop.raise_()
        self.btn_Copy.raise_()
        self.btn_Paste.raise_()
        self.btn_Delete.raise_()
        self.line_2.raise_()
        self.Picture.raise_()
        self.instruments.raise_()
        self.btn_Select.raise_()
        self.btn_Pipette.raise_()
        self.btn_Eraser.raise_()
        self.lbl_color1.raise_()
        self.lbl_color2.raise_()
        self.color_label1.raise_()
        self.color_label2.raise_()
        self.gridLayoutWidget_2.raise_()
        self.btn_Palette.raise_()
        self.border_styles.raise_()
        self.label_2.raise_()
        self.bg_styles.raise_()
        self.label_3.raise_()
        self.line_3.raise_()
        self.label_4.raise_()
        self.btn_drawRect.raise_()
        self.btn_drawEllipse.raise_()
        self.btn_drawLine.raise_()
        self.btn_drawRRect.raise_()
        self.label_Pos.raise_()
        self.XSArea.raise_()
        self.YSArea.raise_()
        self.WSArea.raise_()
        self.HSArea.raise_()
        self.label_Pos_2.raise_()
        self.label_Pos_3.raise_()
        self.label_Pos_4.raise_()
        self.label_Pos_5.raise_()
        self.btn_Ready.raise_()
        self.btn_Pencil.raise_()
        self.errors.raise_()
        self.Radius.raise_()
        self.label_5.raise_()
        self.btn_Info.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ViGeoPaint"))
        self.Drawing.setText(_translate("MainWindow", "Рисование"))
        self.Effects.setText(_translate("MainWindow", "Эффекты"))
        self.btn_Save.setText(_translate("MainWindow", "Сохранить"))
        self.btn_Open.setText(_translate("MainWindow", "Открыть"))
        self.label.setText(_translate("MainWindow", "Ширина: "))
        self.btn_Crop.setText(_translate("MainWindow", "Обрезать"))
        self.btn_Copy.setText(_translate("MainWindow", "Копировать"))
        self.btn_Paste.setText(_translate("MainWindow", "Вставить"))
        self.btn_Delete.setText(_translate("MainWindow", "Удалить"))
        self.Picture.setText(_translate("MainWindow", "Изображение"))
        self.lbl_color1.setText(_translate("MainWindow", "Цвет №1"))
        self.lbl_color2.setText(_translate("MainWindow", "Цвет №2"))
        self.btn_Palette.setText(_translate("MainWindow", "Цвета"))
        self.label_2.setText(_translate("MainWindow", "Контур"))
        self.label_3.setText(_translate("MainWindow", "Заливка"))
        self.label_4.setText(_translate("MainWindow", "Фигуры"))
        self.label_Pos.setText(_translate("MainWindow", "Позиция (x, y):"))
        self.label_Pos_2.setText(_translate("MainWindow", "X:"))
        self.label_Pos_3.setText(_translate("MainWindow", "Y:"))
        self.label_Pos_4.setText(_translate("MainWindow", "W:"))
        self.label_Pos_5.setText(_translate("MainWindow", "H:"))
        self.btn_Ready.setText(_translate("MainWindow", "Готово"))
        self.label_5.setText(_translate("MainWindow", "Радиус"))
