# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'effects.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 720)
        MainWindow.setMinimumSize(QtCore.QSize(600, 360))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 720))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.Drawing = QtWidgets.QPushButton(self.centralwidget)
        self.Drawing.setGeometry(QtCore.QRect(0, 0, 130, 30))
        self.Drawing.setMinimumSize(QtCore.QSize(130, 30))
        self.Drawing.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Drawing.setFont(font)
        self.Drawing.setStyleSheet("border: none; background-color: rgb(126, 87, 194)")
        self.Drawing.setObjectName("Drawing")
        self.Effects = QtWidgets.QPushButton(self.centralwidget)
        self.Effects.setGeometry(QtCore.QRect(260, 0, 130, 30))
        self.Effects.setMinimumSize(QtCore.QSize(130, 30))
        self.Effects.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Effects.setFont(font)
        self.Effects.setStyleSheet("border: none; background-color: rgb(209, 196, 255)")
        self.Effects.setObjectName("Effects")
        self.Area = QtWidgets.QScrollArea(self.centralwidget)
        self.Area.setGeometry(QtCore.QRect(70, 120, 1120, 550))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Area.setPalette(palette)
        self.Area.setAutoFillBackground(False)
        self.Area.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.Area.setFrameShape(QtWidgets.QFrame.Box)
        self.Area.setLineWidth(1)
        self.Area.setMidLineWidth(1)
        self.Area.setWidgetResizable(True)
        self.Area.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Area.setObjectName("Area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1114, 544))
        self.scrollAreaWidgetContents.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Area.setWidget(self.scrollAreaWidgetContents)
        self.btn_Select = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Select.setGeometry(QtCore.QRect(10, 125, 50, 50))
        self.btn_Select.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Select.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Select.setText("")
        self.btn_Select.setIconSize(QtCore.QSize(40, 40))
        self.btn_Select.setObjectName("btn_Select")
        self.Picture = QtWidgets.QPushButton(self.centralwidget)
        self.Picture.setGeometry(QtCore.QRect(130, 0, 130, 30))
        self.Picture.setMinimumSize(QtCore.QSize(130, 30))
        self.Picture.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Picture.setFont(font)
        self.Picture.setStyleSheet("border: none; background-color: rgb(126, 87, 194)")
        self.Picture.setObjectName("Picture")
        self.instruments = QtWidgets.QPushButton(self.centralwidget)
        self.instruments.setGeometry(QtCore.QRect(5, 120, 60, 291))
        self.instruments.setMinimumSize(QtCore.QSize(60, 60))
        self.instruments.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.instruments.setFont(font)
        self.instruments.setStyleSheet("border: none; background-color: rgb(209, 196, 255)")
        self.instruments.setText("")
        self.instruments.setObjectName("instruments")
        self.drawing_buttons = QtWidgets.QPushButton(self.centralwidget)
        self.drawing_buttons.setGeometry(QtCore.QRect(0, 30, 1200, 80))
        self.drawing_buttons.setMinimumSize(QtCore.QSize(130, 80))
        self.drawing_buttons.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drawing_buttons.setFont(font)
        self.drawing_buttons.setStyleSheet("border: none; background-color: rgb(209, 196, 255)")
        self.drawing_buttons.setText("")
        self.drawing_buttons.setObjectName("drawing_buttons")
        self.btn_Crop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Crop.setGeometry(QtCore.QRect(10, 190, 50, 50))
        self.btn_Crop.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Crop.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Crop.setText("")
        self.btn_Crop.setIconSize(QtCore.QSize(40, 40))
        self.btn_Crop.setObjectName("btn_Crop")
        self.btn_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Delete.setGeometry(QtCore.QRect(10, 245, 50, 50))
        self.btn_Delete.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Delete.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Delete.setText("")
        self.btn_Delete.setIconSize(QtCore.QSize(40, 40))
        self.btn_Delete.setObjectName("btn_Delete")
        self.btn_Copy = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Copy.setGeometry(QtCore.QRect(10, 300, 50, 50))
        self.btn_Copy.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Copy.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Copy.setText("")
        self.btn_Copy.setIconSize(QtCore.QSize(40, 40))
        self.btn_Copy.setObjectName("btn_Copy")
        self.btn_Paste = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Paste.setGeometry(QtCore.QRect(10, 355, 50, 50))
        self.btn_Paste.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Paste.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Paste.setText("")
        self.btn_Paste.setIconSize(QtCore.QSize(40, 40))
        self.btn_Paste.setObjectName("btn_Paste")
        self.btn_Invert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Invert.setGeometry(QtCore.QRect(10, 35, 80, 70))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Invert.setFont(font)
        self.btn_Invert.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Invert.setObjectName("btn_Invert")
        self.label_Pos = QtWidgets.QLabel(self.centralwidget)
        self.label_Pos.setGeometry(QtCore.QRect(70, 680, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Pos.setFont(font)
        self.label_Pos.setObjectName("label_Pos")
        self.XSArea = QtWidgets.QSpinBox(self.centralwidget)
        self.XSArea.setGeometry(QtCore.QRect(550, 683, 90, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.XSArea.setFont(font)
        self.XSArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.XSArea.setFrame(False)
        self.XSArea.setMinimum(-99999)
        self.XSArea.setMaximum(99999)
        self.XSArea.setProperty("value", 0)
        self.XSArea.setObjectName("XSArea")
        self.YSArea = QtWidgets.QSpinBox(self.centralwidget)
        self.YSArea.setGeometry(QtCore.QRect(720, 683, 90, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.YSArea.setFont(font)
        self.YSArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.YSArea.setFrame(False)
        self.YSArea.setMinimum(-99999)
        self.YSArea.setMaximum(99999)
        self.YSArea.setProperty("value", 0)
        self.YSArea.setObjectName("YSArea")
        self.label_Pos_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_Pos_5.setGeometry(QtCore.QRect(1055, 680, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Pos_5.setFont(font)
        self.label_Pos_5.setStyleSheet("background-color: rgb(209, 196, 255)")
        self.label_Pos_5.setObjectName("label_Pos_5")
        self.WSArea = QtWidgets.QSpinBox(self.centralwidget)
        self.WSArea.setGeometry(QtCore.QRect(910, 683, 90, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WSArea.setFont(font)
        self.WSArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WSArea.setFrame(False)
        self.WSArea.setMinimum(-99999)
        self.WSArea.setMaximum(99999)
        self.WSArea.setProperty("value", 0)
        self.WSArea.setObjectName("WSArea")
        self.label_Pos_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Pos_3.setGeometry(QtCore.QRect(685, 680, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Pos_3.setFont(font)
        self.label_Pos_3.setStyleSheet("background-color: rgb(209, 196, 255)")
        self.label_Pos_3.setObjectName("label_Pos_3")
        self.label_Pos_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Pos_2.setGeometry(QtCore.QRect(515, 680, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Pos_2.setFont(font)
        self.label_Pos_2.setStyleSheet("background-color: rgb(209, 196, 255)")
        self.label_Pos_2.setObjectName("label_Pos_2")
        self.HSArea = QtWidgets.QSpinBox(self.centralwidget)
        self.HSArea.setGeometry(QtCore.QRect(1090, 683, 90, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HSArea.setFont(font)
        self.HSArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.HSArea.setFrame(False)
        self.HSArea.setMinimum(-99999)
        self.HSArea.setMaximum(99999)
        self.HSArea.setProperty("value", 0)
        self.HSArea.setObjectName("HSArea")
        self.drawing_buttons_2 = QtWidgets.QPushButton(self.centralwidget)
        self.drawing_buttons_2.setGeometry(QtCore.QRect(380, 680, 810, 30))
        self.drawing_buttons_2.setMinimumSize(QtCore.QSize(130, 30))
        self.drawing_buttons_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drawing_buttons_2.setFont(font)
        self.drawing_buttons_2.setStyleSheet("border: none; background-color: rgb(209, 196, 255)")
        self.drawing_buttons_2.setText("")
        self.drawing_buttons_2.setObjectName("drawing_buttons_2")
        self.label_Pos_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_Pos_4.setGeometry(QtCore.QRect(875, 680, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Pos_4.setFont(font)
        self.label_Pos_4.setStyleSheet("background-color: rgb(209, 196, 255)")
        self.label_Pos_4.setObjectName("label_Pos_4")
        self.btn_Ready = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Ready.setGeometry(QtCore.QRect(385, 683, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Ready.setFont(font)
        self.btn_Ready.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_Ready.setObjectName("btn_Ready")
        self.errors = QtWidgets.QLabel(self.centralwidget)
        self.errors.setGeometry(QtCore.QRect(600, 0, 600, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.errors.setFont(font)
        self.errors.setText("")
        self.errors.setObjectName("errors")
        self.btn_Info = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Info.setGeometry(QtCore.QRect(10, 660, 50, 50))
        self.btn_Info.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Info.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_Info.setStyleSheet("border-radius: 25px;\n"
"background-color: rgba(209, 196, 255, 150);")
        self.btn_Info.setText("")
        self.btn_Info.setIconSize(QtCore.QSize(40, 40))
        self.btn_Info.setObjectName("btn_Info")
        self.drawing_buttons_2.raise_()
        self.drawing_buttons.raise_()
        self.Drawing.raise_()
        self.Effects.raise_()
        self.Picture.raise_()
        self.instruments.raise_()
        self.btn_Select.raise_()
        self.btn_Crop.raise_()
        self.btn_Delete.raise_()
        self.btn_Copy.raise_()
        self.btn_Paste.raise_()
        self.Area.raise_()
        self.btn_Invert.raise_()
        self.label_Pos.raise_()
        self.XSArea.raise_()
        self.YSArea.raise_()
        self.label_Pos_5.raise_()
        self.WSArea.raise_()
        self.label_Pos_3.raise_()
        self.label_Pos_2.raise_()
        self.HSArea.raise_()
        self.label_Pos_4.raise_()
        self.btn_Ready.raise_()
        self.errors.raise_()
        self.btn_Info.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ViGeoPaint"))
        self.Drawing.setText(_translate("MainWindow", "Рисование"))
        self.Effects.setText(_translate("MainWindow", "Эффекты"))
        self.btn_Select.setWhatsThis(_translate("MainWindow", "Выделить область"))
        self.Picture.setText(_translate("MainWindow", "Изображение"))
        self.btn_Invert.setText(_translate("MainWindow", "Негатив"))
        self.label_Pos.setText(_translate("MainWindow", "Позиция (x, y):"))
        self.label_Pos_5.setText(_translate("MainWindow", "H:"))
        self.label_Pos_3.setText(_translate("MainWindow", "Y:"))
        self.label_Pos_2.setText(_translate("MainWindow", "X:"))
        self.label_Pos_4.setText(_translate("MainWindow", "W:"))
        self.btn_Ready.setText(_translate("MainWindow", "Готово"))
